name: Test install.sh after release

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  test-install:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      BIN_DIR: $HOME/.local/bin

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🧪 Run install.sh --dry-run
        run: |
          set -euo pipefail
          bash install.sh --dry-run

      - name: 🧪 Install latest release
        run: |
          set -euo pipefail
          mkdir -p "$BIN_DIR"

          VERSION=$(gh release list --limit 1 --repo ${{ github.repository }} --json tagName --jq '.[0].tagName')
          echo "👉 Installing version: $VERSION"

          VERSION="$VERSION" bash install.sh --prefix "$BIN_DIR" --force
        env:
          GH_TOKEN: ${{ github.token }}


      - name: ✅ Check version (direct path)
        run: ${{ env.BIN_DIR }}/context-for-ai --version

      - name: ✅ Check version from PATH
        run: context-for-ai --version
        env:
          PATH: ${{ env.BIN_DIR }}:$PATH

      - name: ✅ Check help from PATH
        run: context-for-ai --help
        env:
          PATH: ${{ env.BIN_DIR }}:$PATH
