name: Install Script Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  install-test:
    name: 🔧 Test install.sh via curl | bash
    runs-on: ubuntu-latest

    steps:
      - name: 🧪 Run install.sh via curl
        run: |
          curl -sSL https://raw.githubusercontent.com/karle0wne/context-for-ai/main/install.sh | bash

      - name: ✅ Verify context-for-ai is installed and working
        run: |
          context-for-ai --version
